\LoadClass[11pt,a4paper,sans]{moderncv}% possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')


% moderncv themes
\moderncvstyle{banking}                            % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{blue}                                % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}          
\RequirePackage{geometry} % changes margins across the page
 \geometry{
 left=10mm,
 right=10mm,
 top=10mm,
 bottom=5mm,
}
\RequirePackage{amssymb}
\RequirePackage{fontawesome5}

\newcommand{\college}{Virginia Tech}

% personal data
\name{Alex `A.J'}{Norton}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted

\address{2422 Nottingham Drive}{Falls Church, Virginia, 22043}{USA}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
\phone[mobile]{+1~(571)~405~0833}                   % optional, remove / comment the line if not wanted
\email{alex.norton.dev@gmail.com}
\homepage{linkedin.com/in/ajnorton}
\social[github][github.com/ajn123]{ajn123}

%\social[linkedin][linkedin.com/in/ajnorton]{ajnorton}
